services:
  oracle-hospital:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-hospital
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=admin123  # Password for SYS and SYSTEM
    volumes:
      - ./db_scripts/init:/opt/oracle/scripts/startup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "hospital/hospital123@//localhost:1521/FREEPDB1", "@/opt/oracle/scripts/startup/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
